FlashCardApp/Models/Deck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FlashCardApp.Models
{
    public class Deck
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public virtual ICollection<Card> Flashcards { get; set; }
    }
}

FlashCardApp/Controllers/DeckController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlashCardApp.Models;
using Microsoft.AspNet.Identity;

namespace FlashCardApp.Controllers
{
    public class DeckController : Controller
    {
        FlashCardAppDb db = new FlashCardAppDb();

        [Authorize]
        public ActionResult Index()
        {
            var user = User.Identity.GetUserId();

            var model = (from d in db.Decks
                         where d.UserId == user
                         select d).ToList();

            return View(model);
        }
           
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,UserId")] Deck deck)
        {
            deck.UserId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Decks.Add(deck);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deck);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deck deck = db.Decks.Find(id);
            if (deck == null)
            {
                return HttpNotFound();
            }
            return View(deck);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,UserId")] Deck deck)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deck).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deck);
        }

        
        public ActionResult Delete(int? id)
        {
       
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deck deck = db.Decks.Find(id);
            if (deck == null)
            {
                return HttpNotFound();
            }
            return View(deck);
        }

        // POST: /Deck/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<Card> cards = (from c in db.Cards
                                where c.DeckId == id
                                select c).ToList();

            foreach (var c in cards)
            {
                db.Cards.Remove(c);
            }

            Deck deck = db.Decks.Find(id);
            db.Decks.Remove(deck);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult ViewCardsFromDeck(int? id)
        {
            var model = db.Decks.Find(id);
            string deckName = db.Decks.Find(id).Name;
            

            ViewBag.Message = deckName;
            ViewBag.DeckId = id;

            return View(model);
        }


        public ActionResult CycleThroughDeck(int? id, int index = 0)
        {
            
            var cards = (from c in db.Cards
                         where c.DeckId == id
                         select c).ToArray();

            var max = cards.Count();
            if (max == 0)
            {
                TempData["notice"] = "There are no cards in that deck to study. Please add cards and try again.";
                return RedirectToAction("Index");
            }
            else
            {
                var currentCard = cards[index];

                if (index == 0 && max == 1)
                {
                    ViewBag.PreviousIndex = index;
                    ViewBag.NextIndex = index;
                }
                else if (index == 0)
                {
                    ViewBag.PreviousIndex = max - 1;
                    ViewBag.NextIndex = 1;
                }
                else if (index == 0 && max == 1)
                {
                    ViewBag.PreviousIndex = index;
                    ViewBag.NextIndex = index;
                }
                else if (index == max - 1 && index != 0)
                {
                    ViewBag.PreviousIndex = index - 1;
                    ViewBag.NextIndex = 0;
                }
                else
                {
                    ViewBag.PreviousIndex = index - 1;
                    ViewBag.NextIndex = index + 1;
                }

                return View(currentCard);
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlashCardApp/Views/Deck/Create.cshtml
@model FlashCardApp.Models.Deck

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Deck</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () { $("#form-group").attr("autocomplete", "off"); });
    </script>
}

FlashCardApp/Views/Deck/CycleThroughDeck.cshtml
@model FlashCardApp.Models.Card

@{
    ViewBag.Title = "CycleThroughDeck";
    
}

<div class="cycleHeader" >
    <h4>Study Cards</h4>
    @Html.ActionLink("Back to List", "ViewCardsFromDeck", "Deck", new { id = ViewBag.Id }, null)
</div>

<div id="flashcard">
    <div id="flashcardContainer">
        <div class="span4 offset4 card">
            <div class="front">@Model.Term</div>

            <div class="back" >@Model.Definition</div>
        </div>
    </div>

    <div id="flashcardControls" class="span4 offset4 text-center controls">
            @if (ViewBag.PreviousIndex != null)
            {
                <div id="previousCard" class="col-lg-4">
                    @Html.ActionLink("Previous", "CycleThroughDeck", "Deck", new { index = ViewBag.PreviousIndex }, new { @class = "btn btn-default fcButton " })
                </div>
            }

            <button type="button" class="btn btn-primary text-center col-lg-4" id="flipCard" onclick="flip()">Flip Card</button>

            @if (ViewBag.NextIndex != null)
            {
                <div id="nextCard" class="col-lg-4">
                    @Html.ActionLink("Next", "CycleThroughDeck", "Deck", new { index = ViewBag.NextIndex }, new { @class = "btn btn-default fcButton" })
                </div>
            }
   
    </div>
</div>






@section scripts{
    <script type="text/javascript">
               
        function flip() {
            $('.card').toggleClass('flipped');
        }

    </script>

}

FlashCardApp/Views/Deck/Delete.cshtml
@model FlashCardApp.Models.Deck

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Deck</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> 
            @Html.ActionLink("Back to List", "Index", "Deck", new { @class = "btn btn-default" })
        </div>
    }
</div>

FlashCardApp/Views/Deck/Edit.cshtml
@model FlashCardApp.Models.Deck

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Deck</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlashCardApp/Views/Deck/Index.cshtml
@model IEnumerable<FlashCardApp.Models.Deck>

@{
    ViewBag.Title = "Home Page";
}

@if (TempData["notice"] != null)
{
    <p>@TempData["notice"]</p>
}

@foreach (var item in Model)
{
    <div class="body-content" id="deckDiv">
        <h3>@item.Name</h3>
        <p>
            @Html.ActionLink("Study Deck", "CycleThroughDeck", "Deck", new { id = @item.Id }, new {@class="btn btn-primary" }) 
            @Html.ActionLink("View Flashcards", "ViewCardsFromDeck", "Deck", new { id = @item.Id }, new {@class="btn btn-primary" })
            @Html.ActionLink("Delete Deck", "Delete", "Deck", new {id = @item.Id}, new {@class="btn btn-primary" })
        </p>
        <hr />
    </div>
}
@Html.ActionLink("Add Flashcard Deck", "Create", "Deck", new { @class = "btn btn-default" })

FlashCardApp/Views/Deck/ViewCardsFromDeck.cshtml
@model FlashCardApp.Models.Deck

@{
    //ViewBag.Title = "ViewCardsFromDeck";
    var DeckId = 0;
    
}

<h2>@ViewBag.Message</h2>
<div class="body-content">
    @Html.ActionLink("Study Deck", "CycleThroughDeck", "Deck", new { id = Model.Id }, new { @class = "btn btn-primary" })  
    @Html.ActionLink("Add Flashcard", "Create", "Card", new { deckId = Model.Id }, new { @class="btn btn-primary" })
</div>

<br/>


@Html.Partial("_Cards", Model.Flashcards)